import type { ClientTestCase } from '../types';

export const cronsCases: ClientTestCase[] = [
  {
    module: 'crons',
    method: 'list',
    http: 'GET',
    path: '/crons',
    scope: 'crons',
    description: '获取定时任务列表',
    argsJson: '[{"searchValue":"","page":1,"size":20}]',
  },
  {
    module: 'crons',
    method: 'detail',
    http: 'GET',
    path: '/crons/detail',
    scope: 'crons',
    description: '按 log_path 查询单个定时任务',
    argsJson: '[{"log_path":"xxx/yyy"}]',
  },
  {
    module: 'crons',
    method: 'getById',
    http: 'GET',
    path: '/crons/:id',
    scope: 'crons',
    description: '按 ID 获取定时任务',
    argsJson: '[1]',
  },
  {
    module: 'crons',
    method: 'create',
    http: 'POST',
    path: '/crons',
    scope: 'crons',
    description: '创建定时任务',
    argsJson:
      '[{"command":"node test.js","schedule":"0 0 * * *","name":"测试任务","labels":["test"]}]',
  },
  {
    module: 'crons',
    method: 'update',
    http: 'PUT',
    path: '/crons',
    scope: 'crons',
    description: '更新定时任务',
    argsJson:
      '[{"id":1,"command":"node test.js","schedule":"0 0 * * *","name":"测试任务"}]',
  },
  {
    module: 'crons',
    method: 'delete',
    http: 'DELETE',
    path: '/crons',
    scope: 'crons',
    description: '批量删除定时任务',
    argsJson: '[[1]]',
    destructive: true,
  },
  {
    module: 'crons',
    method: 'run',
    http: 'PUT',
    path: '/crons/run',
    scope: 'crons',
    description: '运行定时任务',
    argsJson: '[[1]]',
  },
  {
    module: 'crons',
    method: 'stop',
    http: 'PUT',
    path: '/crons/stop',
    scope: 'crons',
    description: '停止定时任务',
    argsJson: '[[1]]',
  },
  {
    module: 'crons',
    method: 'disable',
    http: 'PUT',
    path: '/crons/disable',
    scope: 'crons',
    description: '禁用定时任务',
    argsJson: '[[1]]',
  },
  {
    module: 'crons',
    method: 'enable',
    http: 'PUT',
    path: '/crons/enable',
    scope: 'crons',
    description: '启用定时任务',
    argsJson: '[[1]]',
  },
  {
    module: 'crons',
    method: 'pin',
    http: 'PUT',
    path: '/crons/pin',
    scope: 'crons',
    description: '置顶定时任务',
    argsJson: '[[1]]',
  },
  {
    module: 'crons',
    method: 'unpin',
    http: 'PUT',
    path: '/crons/unpin',
    scope: 'crons',
    description: '取消置顶定时任务',
    argsJson: '[[1]]',
  },
  {
    module: 'crons',
    method: 'updateStatus',
    http: 'PUT',
    path: '/crons/status',
    scope: 'crons',
    description: '更新定时任务运行状态',
    argsJson: '[{"ids":[1],"status":0}]',
  },
  {
    module: 'crons',
    method: 'addLabels',
    http: 'POST',
    path: '/crons/labels',
    scope: 'crons',
    description: '添加标签',
    argsJson: '[{"ids":[1],"labels":["test"]}]',
  },
  {
    module: 'crons',
    method: 'removeLabels',
    http: 'DELETE',
    path: '/crons/labels',
    scope: 'crons',
    description: '移除标签',
    argsJson: '[{"ids":[1],"labels":["test"]}]',
  },
  {
    module: 'crons',
    method: 'import',
    http: 'GET',
    path: '/crons/import',
    scope: 'crons',
    description: '从 crontab 文件导入',
    argsJson: '[]',
  },
  {
    module: 'crons',
    method: 'getLog',
    http: 'GET',
    path: '/crons/:id/log',
    scope: 'crons',
    description: '获取任务当前日志',
    argsJson: '[1]',
  },
  {
    module: 'crons',
    method: 'getLogs',
    http: 'GET',
    path: '/crons/:id/logs',
    scope: 'crons',
    description: '获取任务日志文件列表',
    argsJson: '[1]',
  },
  {
    module: 'crons',
    method: 'getInstances',
    http: 'GET',
    path: '/crons/:id/instances',
    scope: 'crons',
    description: '获取运行中的实例列表',
    argsJson: '[1]',
  },
  {
    module: 'crons',
    method: 'stopInstance',
    http: 'POST',
    path: '/crons/:id/instances/:instanceId/stop',
    scope: 'crons',
    description: '停止指定运行实例',
    argsJson: '[1, 1]',
  },
  {
    module: 'crons',
    method: 'listViews',
    http: 'GET',
    path: '/crons/views',
    scope: 'crons',
    description: '获取视图列表',
    argsJson: '[]',
  },
  {
    module: 'crons',
    method: 'createView',
    http: 'POST',
    path: '/crons/views',
    scope: 'crons',
    description: '创建视图',
    argsJson: '[{"name":"我的视图"}]',
  },
  {
    module: 'crons',
    method: 'updateView',
    http: 'PUT',
    path: '/crons/views',
    scope: 'crons',
    description: '更新视图',
    argsJson: '[{"id":1,"name":"我的视图"}]',
  },
  {
    module: 'crons',
    method: 'deleteViews',
    http: 'DELETE',
    path: '/crons/views',
    scope: 'crons',
    description: '删除视图',
    argsJson: '[[1]]',
    destructive: true,
  },
  {
    module: 'crons',
    method: 'moveView',
    http: 'PUT',
    path: '/crons/views/move',
    scope: 'crons',
    description: '移动视图位置',
    argsJson: '[{"id":1,"fromIndex":0,"toIndex":1}]',
  },
  {
    module: 'crons',
    method: 'disableViews',
    http: 'PUT',
    path: '/crons/views/disable',
    scope: 'crons',
    description: '禁用视图',
    argsJson: '[[1]]',
  },
  {
    module: 'crons',
    method: 'enableViews',
    http: 'PUT',
    path: '/crons/views/enable',
    scope: 'crons',
    description: '启用视图',
    argsJson: '[[1]]',
  },
];
