import type { ClientTestCase } from '../types';

export const dependenciesCases: ClientTestCase[] = [
  {
    module: 'dependencies',
    method: 'list',
    http: 'GET',
    path: '/dependencies',
    scope: 'dependencies',
    description: '获取依赖列表',
    argsJson: '[{"searchValue":""}]',
  },
  {
    module: 'dependencies',
    method: 'getById',
    http: 'GET',
    path: '/dependencies/:id',
    scope: 'dependencies',
    description: '按 ID 获取依赖',
    argsJson: '[1]',
  },
  {
    module: 'dependencies',
    method: 'create',
    http: 'POST',
    path: '/dependencies',
    scope: 'dependencies',
    description: '批量创建依赖',
    argsJson: '[[{"name":"axios","type":0,"remark":"测试"}]]',
  },
  {
    module: 'dependencies',
    method: 'update',
    http: 'PUT',
    path: '/dependencies',
    scope: 'dependencies',
    description: '更新依赖',
    argsJson: '[{"id":1,"name":"axios","type":0,"remark":"更新"}]',
  },
  {
    module: 'dependencies',
    method: 'delete',
    http: 'DELETE',
    path: '/dependencies',
    scope: 'dependencies',
    description: '删除依赖',
    argsJson: '[[1]]',
    destructive: true,
  },
  {
    module: 'dependencies',
    method: 'forceDelete',
    http: 'DELETE',
    path: '/dependencies/force',
    scope: 'dependencies',
    description: '强制删除依赖',
    argsJson: '[[1]]',
    destructive: true,
  },
  {
    module: 'dependencies',
    method: 'reinstall',
    http: 'PUT',
    path: '/dependencies/reinstall',
    scope: 'dependencies',
    description: '重新安装依赖',
    argsJson: '[[1]]',
  },
  {
    module: 'dependencies',
    method: 'cancel',
    http: 'PUT',
    path: '/dependencies/cancel',
    scope: 'dependencies',
    description: '取消安装中的依赖',
    argsJson: '[[1]]',
  },
];
