import type { ClientTestCase } from '../types';

export const envsCases: ClientTestCase[] = [
  {
    module: 'envs',
    method: 'list',
    http: 'GET',
    path: '/envs',
    scope: 'envs',
    description: '获取环境变量列表',
    argsJson: '[{"searchValue":""}]',
  },
  {
    module: 'envs',
    method: 'getById',
    http: 'GET',
    path: '/envs/:id',
    scope: 'envs',
    description: '按 ID 获取单个环境变量',
    argsJson: '[1]',
  },
  {
    module: 'envs',
    method: 'create',
    http: 'POST',
    path: '/envs',
    scope: 'envs',
    description: '批量创建环境变量',
    argsJson:
      '[[{"name":"TEST_VAR","value":"hello","remarks":"测试","labels":["tag1"]}]]',
  },
  {
    module: 'envs',
    method: 'update',
    http: 'PUT',
    path: '/envs',
    scope: 'envs',
    description: '更新环境变量',
    argsJson:
      '[{"id":1,"name":"TEST_VAR","value":"updated","remarks":"更新","labels":["tag1"]}]',
  },
  {
    module: 'envs',
    method: 'delete',
    http: 'DELETE',
    path: '/envs',
    scope: 'envs',
    description: '批量删除环境变量',
    argsJson: '[[1]]',
    destructive: true,
  },
  {
    module: 'envs',
    method: 'move',
    http: 'PUT',
    path: '/envs/:id/move',
    scope: 'envs',
    description: '移动环境变量位置',
    argsJson: '[1, {"fromIndex":0,"toIndex":1}]',
  },
  {
    module: 'envs',
    method: 'disable',
    http: 'PUT',
    path: '/envs/disable',
    scope: 'envs',
    description: '批量禁用环境变量',
    argsJson: '[[1]]',
  },
  {
    module: 'envs',
    method: 'enable',
    http: 'PUT',
    path: '/envs/enable',
    scope: 'envs',
    description: '批量启用环境变量',
    argsJson: '[[1]]',
  },
  {
    module: 'envs',
    method: 'updateNames',
    http: 'PUT',
    path: '/envs/name',
    scope: 'envs',
    description: '批量重命名环境变量',
    argsJson: '[{"ids":[1],"name":"RENAMED_VAR"}]',
  },
  {
    module: 'envs',
    method: 'pin',
    http: 'PUT',
    path: '/envs/pin',
    scope: 'envs',
    description: '置顶环境变量',
    argsJson: '[[1]]',
  },
  {
    module: 'envs',
    method: 'unpin',
    http: 'PUT',
    path: '/envs/unpin',
    scope: 'envs',
    description: '取消置顶环境变量',
    argsJson: '[[1]]',
  },
  {
    module: 'envs',
    method: 'addLabels',
    http: 'POST',
    path: '/envs/labels',
    scope: 'envs',
    description: '添加标签',
    argsJson: '[{"ids":[1],"labels":["tag1"]}]',
  },
  {
    module: 'envs',
    method: 'removeLabels',
    http: 'DELETE',
    path: '/envs/labels',
    scope: 'envs',
    description: '移除标签',
    argsJson: '[{"ids":[1],"labels":["tag1"]}]',
  },
  {
    module: 'envs',
    method: 'upload',
    http: 'POST',
    path: '/envs/upload',
    scope: 'envs',
    description: '上传环境变量 JSON 文件（multipart，字段 env）',
    argsJson: '[]',
    kind: 'file',
  },
];
