import type { ClientTestCase } from '../types';

export const scriptsCases: ClientTestCase[] = [
  {
    module: 'scripts',
    method: 'list',
    http: 'GET',
    path: '/scripts',
    scope: 'scripts',
    description: '获取脚本目录树',
    argsJson: '[{}]',
  },
  {
    module: 'scripts',
    method: 'getDetail',
    http: 'GET',
    path: '/scripts/detail',
    scope: 'scripts',
    description: '读取脚本内容',
    argsJson: '[{"file":"test.js"}]',
  },
  {
    module: 'scripts',
    method: 'getFile',
    http: 'GET',
    path: '/scripts/:file',
    scope: 'scripts',
    description: '按文件名读取脚本',
    argsJson: '["test.js", {}]',
  },
  {
    module: 'scripts',
    method: 'create',
    http: 'POST',
    path: '/scripts',
    scope: 'scripts',
    description: '创建脚本或目录',
    argsJson: '[{"filename":"test.js","content":"console.log(1)"}]',
  },
  {
    module: 'scripts',
    method: 'update',
    http: 'PUT',
    path: '/scripts',
    scope: 'scripts',
    description: '更新脚本内容',
    argsJson: '[{"filename":"test.js","content":"console.log(2)"}]',
  },
  {
    module: 'scripts',
    method: 'delete',
    http: 'DELETE',
    path: '/scripts',
    scope: 'scripts',
    description: '删除脚本或目录',
    argsJson: '[{"filename":"test.js"}]',
    destructive: true,
  },
  {
    module: 'scripts',
    method: 'run',
    http: 'PUT',
    path: '/scripts/run',
    scope: 'scripts',
    description: '运行脚本',
    argsJson: '[{"filename":"test.js"}]',
  },
  {
    module: 'scripts',
    method: 'stop',
    http: 'PUT',
    path: '/scripts/stop',
    scope: 'scripts',
    description: '停止运行中的脚本',
    argsJson: '[{"filename":"test.js"}]',
  },
  {
    module: 'scripts',
    method: 'rename',
    http: 'PUT',
    path: '/scripts/rename',
    scope: 'scripts',
    description: '重命名脚本',
    argsJson: '[{"filename":"test.js","newFilename":"renamed.js"}]',
  },
  {
    module: 'scripts',
    method: 'download',
    http: 'POST',
    path: '/scripts/download',
    scope: 'scripts',
    description: '下载脚本文件',
    argsJson: '[{"filename":"test.js"}]',
  },
];
