import type { ClientTestCase } from '../types';

export const subscriptionsCases: ClientTestCase[] = [
  {
    module: 'subscriptions',
    method: 'list',
    http: 'GET',
    path: '/subscriptions',
    scope: 'subscriptions',
    description: '获取订阅列表',
    argsJson: '[{"searchValue":""}]',
  },
  {
    module: 'subscriptions',
    method: 'getById',
    http: 'GET',
    path: '/subscriptions/:id',
    scope: 'subscriptions',
    description: '按 ID 获取订阅',
    argsJson: '[1]',
  },
  {
    module: 'subscriptions',
    method: 'create',
    http: 'POST',
    path: '/subscriptions',
    scope: 'subscriptions',
    description: '创建订阅',
    argsJson:
      '[{"type":"public-repo","url":"https://github.com/example/repo","alias":"example","schedule_type":"crontab","schedule":"0 0 * * *"}]',
  },
  {
    module: 'subscriptions',
    method: 'update',
    http: 'PUT',
    path: '/subscriptions',
    scope: 'subscriptions',
    description: '更新订阅',
    argsJson:
      '[{"id":1,"type":"public-repo","url":"https://github.com/example/repo","alias":"example","schedule_type":"crontab","schedule":"0 0 * * *"}]',
  },
  {
    module: 'subscriptions',
    method: 'delete',
    http: 'DELETE',
    path: '/subscriptions',
    scope: 'subscriptions',
    description: '删除订阅',
    argsJson: '[[1], {"force":false}]',
    destructive: true,
  },
  {
    module: 'subscriptions',
    method: 'run',
    http: 'PUT',
    path: '/subscriptions/run',
    scope: 'subscriptions',
    description: '运行订阅',
    argsJson: '[[1]]',
  },
  {
    module: 'subscriptions',
    method: 'stop',
    http: 'PUT',
    path: '/subscriptions/stop',
    scope: 'subscriptions',
    description: '停止订阅',
    argsJson: '[[1]]',
  },
  {
    module: 'subscriptions',
    method: 'disable',
    http: 'PUT',
    path: '/subscriptions/disable',
    scope: 'subscriptions',
    description: '禁用订阅',
    argsJson: '[[1]]',
  },
  {
    module: 'subscriptions',
    method: 'enable',
    http: 'PUT',
    path: '/subscriptions/enable',
    scope: 'subscriptions',
    description: '启用订阅',
    argsJson: '[[1]]',
  },
  {
    module: 'subscriptions',
    method: 'updateStatus',
    http: 'PUT',
    path: '/subscriptions/status',
    scope: 'subscriptions',
    description: '更新订阅运行状态',
    argsJson: '[{"ids":[1],"status":0}]',
  },
  {
    module: 'subscriptions',
    method: 'getLog',
    http: 'GET',
    path: '/subscriptions/:id/log',
    scope: 'subscriptions',
    description: '获取订阅当前日志',
    argsJson: '[1]',
  },
  {
    module: 'subscriptions',
    method: 'getLogs',
    http: 'GET',
    path: '/subscriptions/:id/logs',
    scope: 'subscriptions',
    description: '获取订阅日志文件列表',
    argsJson: '[1]',
  },
];
