import type { ClientTestCase } from '../types';

export const systemCases: ClientTestCase[] = [
  {
    module: 'system',
    method: 'info',
    http: 'GET',
    path: '/system',
    description: '获取系统信息（无需鉴权）',
    argsJson: '[]',
  },
  {
    module: 'system',
    method: 'getConfig',
    http: 'GET',
    path: '/system/config',
    scope: 'system',
    description: '获取系统配置',
    argsJson: '[]',
  },
  {
    module: 'system',
    method: 'notify',
    http: 'PUT',
    path: '/system/notify',
    scope: 'system',
    description: '发送系统通知',
    argsJson: '[{"title":"测试","content":"Hello from client test"}]',
  },
  {
    module: 'system',
    method: 'commandRun',
    http: 'PUT',
    path: '/system/command-run',
    scope: 'system',
    description: '运行 shell 命令（流式文本）',
    argsJson: '[{"command":"echo hello"}]',
  },
  {
    module: 'system',
    method: 'commandStop',
    http: 'PUT',
    path: '/system/command-stop',
    scope: 'system',
    description: '停止运行中的命令',
    argsJson: '[{"command":"echo hello"}]',
  },
  {
    module: 'system',
    method: 'checkUpdate',
    http: 'PUT',
    path: '/system/update-check',
    scope: 'system',
    description: '检查更新',
    argsJson: '[]',
  },
  {
    module: 'system',
    method: 'update',
    http: 'PUT',
    path: '/system/update',
    scope: 'system',
    description: '更新青龙面板',
    argsJson: '[]',
    destructive: true,
  },
  {
    module: 'system',
    method: 'reload',
    http: 'PUT',
    path: '/system/reload',
    scope: 'system',
    description: '重载系统',
    argsJson: '[{}]',
    destructive: true,
  },
  {
    module: 'system',
    method: 'exportData',
    http: 'PUT',
    path: '/system/data/export',
    scope: 'system',
    description: '导出数据（返回压缩包 Blob）',
    argsJson: '[{}]',
  },
  {
    module: 'system',
    method: 'importData',
    http: 'PUT',
    path: '/system/data/import',
    scope: 'system',
    description: '导入数据（multipart 上传 data.tgz）',
    argsJson: '[]',
    kind: 'file',
    destructive: true,
  },
  {
    module: 'system',
    method: 'getLog',
    http: 'GET',
    path: '/system/log',
    scope: 'system',
    description: '获取系统日志（流式文本）',
    argsJson: '[{}]',
  },
  {
    module: 'system',
    method: 'deleteLog',
    http: 'DELETE',
    path: '/system/log',
    scope: 'system',
    description: '删除系统日志',
    argsJson: '[]',
    destructive: true,
  },
  {
    module: 'system',
    method: 'resetAuth',
    http: 'PUT',
    path: '/system/auth/reset',
    scope: 'system',
    description: '重置管理员认证信息',
    argsJson: '[{"retries":5,"twoFactorActivated":false}]',
    destructive: true,
  },
  {
    module: 'system',
    method: 'updateLogRemoveFrequency',
    http: 'PUT',
    path: '/system/config/log-remove-frequency',
    scope: 'system',
    description: '更新日志清理频率',
    argsJson: '[{"logRemoveFrequency":7}]',
  },
  {
    module: 'system',
    method: 'updateCronConcurrency',
    http: 'PUT',
    path: '/system/config/cron-concurrency',
    scope: 'system',
    description: '更新定时任务并发数',
    argsJson: '[{"cronConcurrency":5}]',
  },
  {
    module: 'system',
    method: 'updateDependenceProxy',
    http: 'PUT',
    path: '/system/config/dependence-proxy',
    scope: 'system',
    description: '更新依赖代理',
    argsJson: '[{"dependenceProxy":""}]',
  },
  {
    module: 'system',
    method: 'updateNodeMirror',
    http: 'PUT',
    path: '/system/config/node-mirror',
    scope: 'system',
    description: '更新 Node 镜像（流式文本）',
    argsJson: '[{"nodeMirror":""}]',
  },
  {
    module: 'system',
    method: 'updatePythonMirror',
    http: 'PUT',
    path: '/system/config/python-mirror',
    scope: 'system',
    description: '更新 Python 镜像',
    argsJson: '[{"pythonMirror":""}]',
  },
  {
    module: 'system',
    method: 'updateLinuxMirror',
    http: 'PUT',
    path: '/system/config/linux-mirror',
    scope: 'system',
    description: '更新 Linux 镜像（流式文本）',
    argsJson: '[{"linuxMirror":""}]',
  },
  {
    module: 'system',
    method: 'updateTimezone',
    http: 'PUT',
    path: '/system/config/timezone',
    scope: 'system',
    description: '更新时区',
    argsJson: '[{"timezone":"Asia/Shanghai"}]',
  },
  {
    module: 'system',
    method: 'updateLanguage',
    http: 'PUT',
    path: '/system/config/lang',
    scope: 'system',
    description: '更新语言',
    argsJson: '[{"lang":"zh_CN"}]',
  },
  {
    module: 'system',
    method: 'updateGlobalSshKey',
    http: 'PUT',
    path: '/system/config/global-ssh-key',
    scope: 'system',
    description: '更新全局 SSH Key',
    argsJson: '[{"globalSshKey":""}]',
  },
  {
    module: 'system',
    method: 'cleanDependence',
    http: 'PUT',
    path: '/system/config/dependence-clean',
    scope: 'system',
    description: '清理依赖',
    argsJson: '[{}]',
    destructive: true,
  },
];
